// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3S75Pd_vSltPj-9ViAqXTgdjplJS9iE4',
    appId: '1:497173859432:web:92e93fddc64f2713217fdd',
    messagingSenderId: '497173859432',
    projectId: 'aplikasi2-9ab49',
    authDomain: 'aplikasi2-9ab49.firebaseapp.com',
    storageBucket: 'aplikasi2-9ab49.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3S75Pd_vSltPj-9ViAqXTgdjplJS9iE4',
    appId: '1:497173859432:android:92e93fddc64f2713217fdd',
    messagingSenderId: '497173859432',
    projectId: 'aplikasi2-9ab49',
    authDomain: 'aplikasi2-9ab49.firebaseapp.com',
    storageBucket: 'aplikasi2-9ab49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3S75Pd_vSltPj-9ViAqXTgdjplJS9iE4',
    appId: '1:497173859432:ios:92e93fddc64f2713217fdd',
    messagingSenderId: '497173859432',
    projectId: 'aplikasi2-9ab49',
    authDomain: 'aplikasi2-9ab49.firebaseapp.com',
    storageBucket: 'aplikasi2-9ab49.firebasestorage.app',
    iosBundleId: 'com.example.aplikasi2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3S75Pd_vSltPj-9ViAqXTgdjplJS9iE4',
    appId: '1:497173859432:ios:92e93fddc64f2713217fdd',
    messagingSenderId: '497173859432',
    projectId: 'aplikasi2-9ab49',
    authDomain: 'aplikasi2-9ab49.firebaseapp.com',
    storageBucket: 'aplikasi2-9ab49.firebasestorage.app',
    iosBundleId: 'com.example.aplikasi2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3S75Pd_vSltPj-9ViAqXTgdjplJS9iE4',
    appId: '1:497173859432:web:92e93fddc64f2713217fdd',
    messagingSenderId: '497173859432',
    projectId: 'aplikasi2-9ab49',
    authDomain: 'aplikasi2-9ab49.firebaseapp.com',
    storageBucket: 'aplikasi2-9ab49.firebasestorage.app',
  );
}
